services:
  message-bus:
    image: nats:2.11.0-alpine3.21
    ports:
      - "4222:4222"

  discovery:
    build: ./discovery
    depends_on:
      - message-bus
  
  notifier:
    build: ./notifier
    depends_on:
      - message-bus
