services:
  message-bus:
    image: nats:2.11.0-alpine3.21
    ports:
      - "4222:4222"

  discovery:
    build: ./discovery
    depends_on:
      - message-bus
  
  notifier:
    build: ./notifier
    depends_on:
      - message-bus

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  historian:
    build: ./historian
    depends_on:
      - mongodb

volumes:
  mongodb_data:
